//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.20506.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BaseResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaseResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaseLibrary.BaseResource", typeof(BaseResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molecular Biology.
        /// </summary>
        public static string Application_Name {
            get {
                return ResourceManager.GetString("Application_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restriction digestion functionality will be disable..
        /// </summary>
        public static string Enzyme_Error_Disable {
            get {
                return ResourceManager.GetString("Enzyme_Error_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Rebase file..
        /// </summary>
        public static string Enzyme_Error_File_Parse {
            get {
                return ResourceManager.GetString("Enzyme_Error_File_Parse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Error_DllLoad {
            get {
                return ResourceManager.GetString("Error_DllLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found..
        /// </summary>
        public static string Error_File_Not_Found {
            get {
                return ResourceManager.GetString("Error_File_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required file not found..
        /// </summary>
        public static string Error_File_Not_Found_Required {
            get {
                return ResourceManager.GetString("Error_File_Not_Found_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the file name and try again..
        /// </summary>
        public static string Error_File_Not_Found_Try_Again {
            get {
                return ResourceManager.GetString("Error_File_Not_Found_Try_Again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading file..
        /// </summary>
        public static string Error_File_Parse {
            get {
                return ResourceManager.GetString("Error_File_Parse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error running Needleman-Wunsch alignment..
        /// </summary>
        public static string Error_NcbiTk_Nwalign {
            get {
                return ResourceManager.GetString("Error_NcbiTk_Nwalign", resourceCulture);
            }
        }
    }
}
